/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/audit-log/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List recent audit log entries (Platform Admin only)
         * @description Returns audit entries newest-first. Filter by school_id to scope results to a specific school. Leave school_id unset to see platform-wide entries.
         */
        get: operations["list_audit_log_api_v1_admin_audit_log__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/disclaimer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all Disclaimer versions (admin) */
        get: operations["admin_list_disclaimer_api_v1_admin_disclaimer_get"];
        put?: never;
        /** Publish a new Disclaimer version */
        post: operations["publish_disclaimer_api_v1_admin_disclaimer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/exam-syllabi/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all exam syllabi */
        get: operations["list_syllabi_api_v1_admin_exam_syllabi__get"];
        put?: never;
        /** Create a new exam syllabus */
        post: operations["create_syllabus_api_v1_admin_exam_syllabi__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/exam-syllabi/{syllabus_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single exam syllabus */
        get: operations["get_syllabus_api_v1_admin_exam_syllabi__syllabus_id__get"];
        /** Update an exam syllabus (bumps version_number) */
        put: operations["update_syllabus_api_v1_admin_exam_syllabi__syllabus_id__put"];
        post?: never;
        /** Soft-delete an exam syllabus */
        delete: operations["delete_syllabus_api_v1_admin_exam_syllabi__syllabus_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/exam-syllabi/{syllabus_id}/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List topics for a syllabus */
        get: operations["list_topics_api_v1_admin_exam_syllabi__syllabus_id__topics_get"];
        put?: never;
        /** Create a topic under a syllabus */
        post: operations["create_topic_api_v1_admin_exam_syllabi__syllabus_id__topics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/exam-syllabi/{syllabus_id}/topics/{topic_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Soft-delete a topic */
        delete: operations["delete_topic_api_v1_admin_exam_syllabi__syllabus_id__topics__topic_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/library/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List platform reference books
         * @description Returns non-deleted books newest-first.
         */
        get: operations["list_library_books_api_v1_admin_library__get"];
        put?: never;
        /**
         * Upload a platform reference book
         * @description Upload a PDF to the Platform Library. Returns 202 immediately; ingestion runs asynchronously on the ingestion worker.
         */
        post: operations["upload_library_book_api_v1_admin_library__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/library/{book_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Soft-delete a platform reference book
         * @description Marks the book deleted. MinIO file and Qdrant embeddings are retained per §5.3 (soft-delete with citations preserved).
         */
        delete: operations["delete_library_book_api_v1_admin_library__book_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/personas/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all teaching personas */
        get: operations["list_personas_api_v1_admin_personas__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/personas/{persona_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single teaching persona */
        get: operations["get_persona_api_v1_admin_personas__persona_id__get"];
        /** Update a teaching persona's prompts or active status */
        put: operations["update_persona_api_v1_admin_personas__persona_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/subscription-tiers/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all subscription tiers */
        get: operations["list_tiers_api_v1_admin_subscription_tiers__get"];
        put?: never;
        /** Create a new subscription tier */
        post: operations["create_tier_api_v1_admin_subscription_tiers__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/subscription-tiers/{tier_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single subscription tier */
        get: operations["get_tier_api_v1_admin_subscription_tiers__tier_id__get"];
        /** Update a subscription tier */
        put: operations["update_tier_api_v1_admin_subscription_tiers__tier_id__put"];
        post?: never;
        /** Soft-delete a subscription tier */
        delete: operations["delete_tier_api_v1_admin_subscription_tiers__tier_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/tos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all ToS versions (admin) */
        get: operations["admin_list_tos_api_v1_admin_tos_get"];
        put?: never;
        /** Publish a new ToS version */
        post: operations["publish_tos_api_v1_admin_tos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/post-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post-OIDC-login handler
         * @description Called by the frontend after every successful Authentik OIDC callback. Creates a User row on first login. Returns ToS acceptance status so the frontend can show the acceptance modal if needed.
         */
        post: operations["post_login_api_v1_auth_post_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/disclaimer/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current Disclaimer version */
        get: operations["get_current_disclaimer_api_v1_disclaimer_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Liveness probe — always returns 200 if the app is running.
         */
        get: operations["health_check_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness Check
         * @description Readiness probe — checks that the app can accept traffic.
         */
        get: operations["readiness_check_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List notifications for the current user
         * @description Returns non-deleted notifications newest-first, with unread count for bell badge.
         */
        get: operations["list_notifications_api_v1_notifications__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/{notif_id}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Mark a notification as read
         * @description The authenticated user may only mark their own notifications as read.
         */
        post: operations["mark_notification_read_api_v1_notifications__notif_id__read_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/smoketest/llm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Smoketest Llm
         * @description Run a sample LLM call.
         */
        post: operations["smoketest_llm_api_v1_smoketest_llm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/smoketest/rag": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Smoketest Rag
         * @description Run a sample RAG query. Returns empty chunks since no content is ingested yet.
         */
        post: operations["smoketest_rag_api_v1_smoketest_rag_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tos/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current ToS version */
        get: operations["get_current_tos_api_v1_tos_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tos/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all ToS versions */
        get: operations["list_tos_versions_api_v1_tos_versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload File
         * @description Upload a file through the pipeline.
         *
         *     Returns 202 Accepted immediately with a tracking URL.
         *     Per ARCH §11.16 canonical endpoint shape.
         */
        post: operations["upload_file_api_v1_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/uploads/{upload_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Upload Status
         * @description Get the status of a previously initiated upload.
         */
        get: operations["get_upload_status_api_v1_uploads__upload_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user profile */
        get: operations["get_me_api_v1_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/me/accept-tos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept the current ToS */
        post: operations["accept_tos_api_v1_users_me_accept_tos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Metrics
         * @description Endpoint that serves Prometheus metrics.
         */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_upload_file_api_v1_uploads_post */
        Body_upload_file_api_v1_uploads_post: {
            /** File */
            file: string;
        };
        /** Body_upload_library_book_api_v1_admin_library__post */
        Body_upload_library_book_api_v1_admin_library__post: {
            /** File */
            file: string;
        };
        /**
         * DisclaimerVersionCreate
         * @description Publish a new Disclaimer version (Platform Admin only). 500-char limit.
         */
        DisclaimerVersionCreate: {
            /** Content */
            content: string;
            /**
             * Language
             * @default en
             */
            language: string;
        };
        /**
         * ExamSyllabusCreate
         * @description Payload for creating a new ExamSyllabus.
         */
        ExamSyllabusCreate: {
            /** Exam Board */
            exam_board: string;
            /** Grade Range Max */
            grade_range_max?: number | null;
            /** Grade Range Min */
            grade_range_min?: number | null;
            /**
             * Language
             * @default en
             */
            language: string;
            /** Name */
            name: string;
            /** Region */
            region?: string | null;
        };
        /**
         * ExamSyllabusUpdate
         * @description Payload for updating an ExamSyllabus (all fields optional).
         */
        ExamSyllabusUpdate: {
            /** Exam Board */
            exam_board?: string | null;
            /** Grade Range Max */
            grade_range_max?: number | null;
            /** Grade Range Min */
            grade_range_min?: number | null;
            /** Language */
            language?: string | null;
            /** Name */
            name?: string | null;
            /** Region */
            region?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LibraryBookListResponse
         * @description Paginated list of platform reference books.
         */
        LibraryBookListResponse: {
            /** Items */
            items: components["schemas"]["LibraryBookRead"][];
            /** Total */
            total: number;
        };
        /**
         * LibraryBookRead
         * @description Full book record returned to the caller.
         */
        LibraryBookRead: {
            /** Chunk Count */
            chunk_count: number | null;
            /** Content Type */
            content_type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Deleted At */
            deleted_at: string | null;
            /** Grade Range Max */
            grade_range_max: number | null;
            /** Grade Range Min */
            grade_range_min: number | null;
            /** Id */
            id: string;
            /** Language */
            language: string;
            /** Qdrant Collection */
            qdrant_collection: string;
            /** Sha256 */
            sha256: string;
            /** Status */
            status: string;
            /** Subject Tag */
            subject_tag: string | null;
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Upload Id */
            upload_id: string;
        };
        /**
         * LibraryUploadResponse
         * @description Returned after POST /admin/library — 202 Accepted.
         */
        LibraryUploadResponse: {
            /** Book Id */
            book_id: string;
            /**
             * Message
             * @default Upload accepted; ingestion queued on the ingestion worker.
             */
            message: string;
            /** Status */
            status: string;
            /** Upload Id */
            upload_id: string;
        };
        /**
         * NotificationListResponse
         * @description Paginated notification list with unread counter for the bell badge.
         */
        NotificationListResponse: {
            /** Items */
            items: components["schemas"]["NotificationRead"][];
            /** Total */
            total: number;
            /** Unread Count */
            unread_count: number;
        };
        /**
         * NotificationRead
         * @description Read schema for a single notification row.
         */
        NotificationRead: {
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Feature Namespace */
            feature_namespace: string;
            /** Id */
            id: string;
            /** Is Read */
            is_read: boolean;
            /** Read At */
            read_at: string | null;
            /** Recipient User Id */
            recipient_user_id: string;
            /** School Id */
            school_id: string | null;
            /** Template Key */
            template_key: string;
            /** Title */
            title: string;
        };
        /**
         * PersonaUpdate
         * @description Payload for updating a TeachingPersona (all fields optional).
         *
         *     Only Platform Admin may call this. Changes apply to NEW sessions only;
         *     in-flight sessions continue using the previously cached system prompt.
         */
        PersonaUpdate: {
            /** Is Active */
            is_active?: boolean | null;
            /** System Prompt En */
            system_prompt_en?: string | null;
            /** System Prompt Ps */
            system_prompt_ps?: string | null;
            /** System Prompt Sd */
            system_prompt_sd?: string | null;
            /** System Prompt Ur */
            system_prompt_ur?: string | null;
        };
        /**
         * SubscriptionTierCreate
         * @description Payload for creating a new SubscriptionTier.
         */
        SubscriptionTierCreate: {
            /**
             * Applies To
             * @enum {string}
             */
            applies_to: "district" | "school";
            /** Caps */
            caps?: {
                [key: string]: unknown;
            } | null;
            /** Description */
            description?: string | null;
            /** Name */
            name: string;
            /**
             * Pricing Monthly Pkr
             * @default 0
             */
            pricing_monthly_pkr: number;
            /** Slug */
            slug: string;
        };
        /**
         * SubscriptionTierUpdate
         * @description Payload for updating a SubscriptionTier (all fields optional).
         */
        SubscriptionTierUpdate: {
            /** Caps */
            caps?: {
                [key: string]: unknown;
            } | null;
            /** Description */
            description?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Name */
            name?: string | null;
            /** Pricing Monthly Pkr */
            pricing_monthly_pkr?: number | null;
        };
        /**
         * SyllabusTopicCreate
         * @description Payload for creating a new SyllabusTopic.
         */
        SyllabusTopicCreate: {
            /**
             * Order Index
             * @default 0
             */
            order_index: number;
            /** Parent Id */
            parent_id?: string | null;
            /** Syllabus Id */
            syllabus_id: string;
            /** Title */
            title: string;
        };
        /**
         * TosAcceptRequest
         * @description User accepts the current ToS.
         */
        TosAcceptRequest: {
            /** Tos Version Id */
            tos_version_id: string;
        };
        /**
         * TosVersionCreate
         * @description Publish a new ToS version (Platform Admin only).
         */
        TosVersionCreate: {
            /** Content Md */
            content_md: string;
            /**
             * Language
             * @default en
             */
            language: string;
        };
        /**
         * UploadInitiated
         * @description Response returned immediately after upload (202 Accepted).
         */
        UploadInitiated: {
            /**
             * Message
             * @default
             */
            message: string;
            status: components["schemas"]["UploadStatus"];
            /** Status Url */
            status_url: string;
            /** Upload Id */
            upload_id: string;
        };
        /**
         * UploadStatus
         * @enum {string}
         */
        UploadStatus: "pending" | "ready" | "failed" | "duplicate";
        /**
         * UploadStatusResponse
         * @description Response for GET /uploads/{id}.
         */
        UploadStatusResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Filename */
            filename: string;
            /** Minio Key */
            minio_key: string;
            /** Profile */
            profile: string;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            status: components["schemas"]["UploadStatus"];
            /** Upload Id */
            upload_id: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_audit_log_api_v1_admin_audit_log__get: {
        parameters: {
            query?: {
                /** @description Filter by school tenant */
                school_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_list_disclaimer_api_v1_admin_disclaimer_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    publish_disclaimer_api_v1_admin_disclaimer_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DisclaimerVersionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_syllabi_api_v1_admin_exam_syllabi__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    create_syllabus_api_v1_admin_exam_syllabi__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExamSyllabusCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_syllabus_api_v1_admin_exam_syllabi__syllabus_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                syllabus_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_syllabus_api_v1_admin_exam_syllabi__syllabus_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                syllabus_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExamSyllabusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_syllabus_api_v1_admin_exam_syllabi__syllabus_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                syllabus_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_topics_api_v1_admin_exam_syllabi__syllabus_id__topics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                syllabus_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_topic_api_v1_admin_exam_syllabi__syllabus_id__topics_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                syllabus_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyllabusTopicCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_topic_api_v1_admin_exam_syllabi__syllabus_id__topics__topic_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                syllabus_id: string;
                topic_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_library_books_api_v1_admin_library__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryBookListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_library_book_api_v1_admin_library__post: {
        parameters: {
            query: {
                title: string;
                content_type?: string;
                subject_tag?: string | null;
                grade_range_min?: number | null;
                grade_range_max?: number | null;
                language?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_library_book_api_v1_admin_library__post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_library_book_api_v1_admin_library__book_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                book_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryBookRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_personas_api_v1_admin_personas__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_persona_api_v1_admin_personas__persona_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                persona_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_persona_api_v1_admin_personas__persona_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                persona_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonaUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tiers_api_v1_admin_subscription_tiers__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    create_tier_api_v1_admin_subscription_tiers__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionTierCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tier_api_v1_admin_subscription_tiers__tier_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tier_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_tier_api_v1_admin_subscription_tiers__tier_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tier_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscriptionTierUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_tier_api_v1_admin_subscription_tiers__tier_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tier_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_list_tos_api_v1_admin_tos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    publish_tos_api_v1_admin_tos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TosVersionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_login_api_v1_auth_post_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_current_disclaimer_api_v1_disclaimer_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health_check_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readiness_check_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_notifications_api_v1_notifications__get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_notification_read_api_v1_notifications__notif_id__read_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notif_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    smoketest_llm_api_v1_smoketest_llm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: string;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    smoketest_rag_api_v1_smoketest_rag_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: string;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_tos_api_v1_tos_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_tos_versions_api_v1_tos_versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    upload_file_api_v1_uploads_post: {
        parameters: {
            query?: {
                profile?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_file_api_v1_uploads_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadInitiated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_upload_status_api_v1_uploads__upload_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                upload_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_v1_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    accept_tos_api_v1_users_me_accept_tos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TosAcceptRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
