/**
 * Generated API types — single source of truth for request/response shapes.
 *
 * Re-exports openapi-typescript output from `schema.d.ts` (regenerated by
 * `pnpm gen:api`). Per AMENDMENTS A-002, frontend types are GENERATED from the
 * backend contract, never hand-mirrored.
 */
import type { components } from "./schema";

type Schemas = components["schemas"];

// ── Request / create types ────────────────────────────────────────────────────
export type ExamSyllabusCreate = Schemas["ExamSyllabusCreate"];
export type ExamSyllabusUpdate = Schemas["ExamSyllabusUpdate"];
export type PersonaUpdate = Schemas["PersonaUpdate"];
export type SubscriptionTierCreate = Schemas["SubscriptionTierCreate"];
export type SubscriptionTierUpdate = Schemas["SubscriptionTierUpdate"];
export type TosVersionCreate = Schemas["TosVersionCreate"];
export type TosAcceptRequest = Schemas["TosAcceptRequest"];

// ── Read / response types (SuccessEnvelope `data` shapes) ─────────────────────
export type PersonaRead = Schemas["PersonaRead"];
export type ExamSyllabusRead = Schemas["ExamSyllabusRead"];
export type SubscriptionTierRead = Schemas["SubscriptionTierRead"];
export type TosVersionRead = Schemas["TosVersionRead"];
export type DisclaimerVersionRead = Schemas["DisclaimerVersionRead"];
export type LibraryBookRead = Schemas["LibraryBookRead"];
export type LibraryBookListResponse = Schemas["LibraryBookListResponse"];
export type AuditLogEntryRead = Schemas["AuditLogEntryRead"];
export type AuditLogListResponse = Schemas["PaginatedEnvelope_AuditLogEntryRead_"];
export type NotificationRead = Schemas["NotificationRead"];
export type PostLoginResponse = Schemas["PostLoginResponse"];
export type TosAcceptResponse = Schemas["TosAcceptResponse"];
export type TosDeclineResponse = Schemas["TosDeclineResponse"];

/** View-model aliases used by admin components (maps API field names). */
export type Persona = PersonaRead;
export type Syllabus = ExamSyllabusRead;
export type SubscriptionTier = SubscriptionTierRead;
export type AuditEntry = AuditLogEntryRead;
export type Notification = NotificationRead;

export interface TosVersion {
  id: string;
  version: number;
  content: string;
  effective_at: string;
}
