/**
 * Generated API types — single source of truth for request/response shapes.
 *
 * These re-export the openapi-typescript output in `schema.d.ts` (regenerated by
 * `pnpm gen:api` from the backend OpenAPI). Per AMENDMENTS A-002, frontend types
 * are GENERATED from the backend contract, never hand-mirrored — the
 * typed-client-drift CI gate fails the PR if `schema.d.ts` is stale.
 *
 * T-224 establishes this re-export pattern on the components available today.
 * T-225 wires `response_model=SuccessEnvelope[XxxRead]` on every route (so the
 * Read schemas appear here), and T-233 migrates the remaining hand-mirrored
 * interfaces in `index.ts` onto these generated types and deletes them.
 */
import type { components } from "./schema";

type Schemas = components["schemas"];

export type ExamSyllabusCreate = Schemas["ExamSyllabusCreate"];
export type ExamSyllabusUpdate = Schemas["ExamSyllabusUpdate"];
export type PersonaUpdate = Schemas["PersonaUpdate"];
export type SubscriptionTierCreate = Schemas["SubscriptionTierCreate"];
export type SubscriptionTierUpdate = Schemas["SubscriptionTierUpdate"];
export type TosVersionCreate = Schemas["TosVersionCreate"];
export type TosAcceptRequest = Schemas["TosAcceptRequest"];
export type LibraryBookRead = Schemas["LibraryBookRead"];
export type NotificationRead = Schemas["NotificationRead"];
