"""School migration: student_highlights (T-185).

Revision ID: school_0073
Revises: school_0072
Create Date: 2026-10-03

Purpose: persist lecture highlights (Flow 6 §3.6 / #58) — anchor (paragraph
ordinal + offset/length), highlighted text, ai_response_ref (question_id),
concept tag, tenant_type. Soft-delete per flow-6 §5.5.
Risk: low — additive table; reuses existing lectures_tenant_type_enum.
Reversible: yes

Autogenerated from SchoolStudentHighlight and pruned to this table only
(the autogenerate diff also carried pre-existing, unrelated model drift).
"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "school_0073"
down_revision: str = "school_0072"
branch_labels: tuple[()] = ()
depends_on: str | None = None

_SCHEMA = "school"


def upgrade() -> None:
    # Created by school_0051 — reference only, never re-create.
    tenant_type_enum = postgresql.ENUM(
        "school",
        "independent",
        name="lectures_tenant_type_enum",
        schema=_SCHEMA,
        create_type=False,
    )
    op.create_table(
        "student_highlights",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("student_user_id", sa.String(length=36), nullable=False),
        sa.Column("lecture_id", sa.String(length=36), nullable=False),
        sa.Column("lecture_version_id", sa.String(length=36), nullable=True),
        sa.Column("paragraph_id", sa.String(length=36), nullable=True),
        sa.Column("paragraph_ordinal", sa.Integer(), nullable=False),
        sa.Column("text_range_offset", sa.Integer(), nullable=False),
        sa.Column("text_range_length", sa.Integer(), nullable=False),
        sa.Column("highlighted_text", sa.Text(), nullable=False),
        sa.Column("question_id", sa.String(length=36), nullable=True),
        sa.Column("concept_tag", sa.String(length=128), nullable=True),
        sa.Column("tenant_type", tenant_type_enum, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(now() AT TIME ZONE 'UTC')"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(now() AT TIME ZONE 'UTC')"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "paragraph_ordinal >= 0", name="student_highlights_paragraph_ordinal_nonneg_check"
        ),
        sa.CheckConstraint(
            "text_range_length > 0", name="student_highlights_length_positive_check"
        ),
        sa.CheckConstraint("text_range_offset >= 0", name="student_highlights_offset_nonneg_check"),
        sa.ForeignKeyConstraint(["lecture_id"], ["school.lectures.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["lecture_version_id"], ["school.lecture_versions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["paragraph_id"], ["school.lecture_paragraphs.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["question_id"], ["school.student_questions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["student_user_id"], ["school.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema=_SCHEMA,
    )
    op.create_index(
        "ix_school_student_highlights_deleted_at",
        "student_highlights",
        ["deleted_at"],
        schema=_SCHEMA,
    )
    op.create_index(
        "ix_student_highlights_lecture_id", "student_highlights", ["lecture_id"], schema=_SCHEMA
    )
    op.create_index(
        "ix_student_highlights_lecture_version_id",
        "student_highlights",
        ["lecture_version_id"],
        schema=_SCHEMA,
    )
    op.create_index(
        "ix_student_highlights_paragraph_id",
        "student_highlights",
        ["paragraph_id"],
        schema=_SCHEMA,
    )
    op.create_index(
        "ix_student_highlights_question_id", "student_highlights", ["question_id"], schema=_SCHEMA
    )
    op.create_index(
        "ix_student_highlights_student_lecture",
        "student_highlights",
        ["student_user_id", "lecture_id"],
        schema=_SCHEMA,
    )


def downgrade() -> None:
    for name in (
        "ix_student_highlights_student_lecture",
        "ix_student_highlights_question_id",
        "ix_student_highlights_paragraph_id",
        "ix_student_highlights_lecture_version_id",
        "ix_student_highlights_lecture_id",
        "ix_school_student_highlights_deleted_at",
    ):
        op.drop_index(name, table_name="student_highlights", schema=_SCHEMA)
    op.drop_table("student_highlights", schema=_SCHEMA)
