"""School migration: student_flashcards (T-186).

Revision ID: school_0074
Revises: school_0073
Create Date: 2026-10-03

Purpose: auto-flashcards from highlight + AI answer pairs (Flow 6 §3.6 / #58):
front = highlight, back = answer, lecture + concept tags, dedupe_hash unique
per student among live rows, tenant_type. SRS state is NOT here (Flow 8/9).
Risk: low — additive table + two new enums.
Reversible: yes

Autogenerated from SchoolStudentFlashcard and pruned to this table only
(the autogenerate diff also carried pre-existing, unrelated model drift).
"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "school_0074"
down_revision: str = "school_0073"
branch_labels: tuple[()] = ()
depends_on: str | None = None

_SCHEMA = "school"


def _create_enum_if_missing(qualified_name: str, values_sql: str) -> None:
    op.execute(
        f"""
        DO $$ BEGIN
            CREATE TYPE {qualified_name} AS ENUM ({values_sql});
        EXCEPTION
            WHEN duplicate_object THEN NULL;
        END $$;
        """
    )


def upgrade() -> None:
    _create_enum_if_missing(
        f"{_SCHEMA}.student_flashcards_source_type_enum", "'highlight', 'manual'"
    )
    _create_enum_if_missing(f"{_SCHEMA}.student_flashcards_status_enum", "'active', 'dismissed'")
    source_type_enum = postgresql.ENUM(
        "highlight",
        "manual",
        name="student_flashcards_source_type_enum",
        schema=_SCHEMA,
        create_type=False,
    )
    status_enum = postgresql.ENUM(
        "active",
        "dismissed",
        name="student_flashcards_status_enum",
        schema=_SCHEMA,
        create_type=False,
    )
    # Created by school_0051 — reference only.
    tenant_type_enum = postgresql.ENUM(
        "school",
        "independent",
        name="lectures_tenant_type_enum",
        schema=_SCHEMA,
        create_type=False,
    )
    op.create_table(
        "student_flashcards",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("student_user_id", sa.String(length=36), nullable=False),
        sa.Column("lecture_id", sa.String(length=36), nullable=True),
        sa.Column("source_type", source_type_enum, nullable=False),
        sa.Column("source_highlight_id", sa.String(length=36), nullable=True),
        sa.Column("concept_tag", sa.String(length=128), nullable=True),
        sa.Column("front_text", sa.Text(), nullable=False),
        sa.Column("back_text", sa.Text(), nullable=False),
        sa.Column("dedupe_hash", sa.String(length=64), nullable=False),
        sa.Column("status", status_enum, nullable=False),
        sa.Column("tenant_type", tenant_type_enum, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(now() AT TIME ZONE 'UTC')"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(now() AT TIME ZONE 'UTC')"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["lecture_id"], ["school.lectures.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["source_highlight_id"], ["school.student_highlights.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["student_user_id"], ["school.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema=_SCHEMA,
    )
    op.create_index(
        "ix_school_student_flashcards_deleted_at",
        "student_flashcards",
        ["deleted_at"],
        schema=_SCHEMA,
    )
    op.create_index(
        "ix_student_flashcards_lecture_id", "student_flashcards", ["lecture_id"], schema=_SCHEMA
    )
    op.create_index(
        "ix_student_flashcards_source_highlight_id",
        "student_flashcards",
        ["source_highlight_id"],
        schema=_SCHEMA,
    )
    op.create_index(
        "ix_student_flashcards_student_created",
        "student_flashcards",
        ["student_user_id", "created_at"],
        schema=_SCHEMA,
    )
    # Dedupe (§3.6): one live card per (student, hash(lecture, highlight text)).
    op.create_index(
        "student_flashcards_student_dedupe_uq",
        "student_flashcards",
        ["student_user_id", "dedupe_hash"],
        unique=True,
        schema=_SCHEMA,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )


def downgrade() -> None:
    for name in (
        "student_flashcards_student_dedupe_uq",
        "ix_student_flashcards_student_created",
        "ix_student_flashcards_source_highlight_id",
        "ix_student_flashcards_lecture_id",
        "ix_school_student_flashcards_deleted_at",
    ):
        op.drop_index(name, table_name="student_flashcards", schema=_SCHEMA)
    op.drop_table("student_flashcards", schema=_SCHEMA)
    op.execute(f"DROP TYPE IF EXISTS {_SCHEMA}.student_flashcards_status_enum")
    op.execute(f"DROP TYPE IF EXISTS {_SCHEMA}.student_flashcards_source_type_enum")
