"""School migration: careers controlled vocabulary table (T-189).

Revision ID: school_0075
Revises: school_0074
Create Date: 2026-10-03

Purpose: platform-level career vocabulary for concept enrichment (flow-6 §3.10)
— the LLM may only link careers by id from this table (T-190).
Risk: low — additive table (seeded separately by school_0076).
Reversible: yes

Autogenerated from Career and pruned to this table only.
"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "school_0075"
down_revision: str = "school_0074"
branch_labels: tuple[()] = ()
depends_on: str | None = None

_SCHEMA = "school"


def upgrade() -> None:
    op.create_table(
        "careers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("sector", sa.String(length=100), nullable=False),
        sa.Column("required_concepts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(now() AT TIME ZONE 'UTC')"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(now() AT TIME ZONE 'UTC')"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug", name="careers_slug_uq"),
        schema=_SCHEMA,
    )
    op.create_index("ix_careers_sector", "careers", ["sector"], schema=_SCHEMA)


def downgrade() -> None:
    op.drop_index("ix_careers_sector", table_name="careers", schema=_SCHEMA)
    op.drop_table("careers", schema=_SCHEMA)
