"""School migration: concept_applications per-concept cache (T-189).

Revision ID: school_0077
Revises: school_0076
Create Date: 2026-10-03

Purpose: per-concept enrichment cache (real-world uses, career ids, mini-sim
spec) shared by all students; unique (concept_id, tenant_type); status doubles
as the generation lock (flow-6 §3.10, T-190).
Risk: low — additive table + one enum.
Reversible: yes

Autogenerated from SchoolConceptApplication and pruned to this table only.
"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "school_0077"
down_revision: str = "school_0076"
branch_labels: tuple[()] = ()
depends_on: str | None = None

_SCHEMA = "school"


def upgrade() -> None:
    op.execute(
        f"""
        DO $$ BEGIN
            CREATE TYPE {_SCHEMA}.concept_applications_status_enum
                AS ENUM ('pending', 'ready', 'failed');
        EXCEPTION
            WHEN duplicate_object THEN NULL;
        END $$;
        """
    )
    status_enum = postgresql.ENUM(
        "pending",
        "ready",
        "failed",
        name="concept_applications_status_enum",
        schema=_SCHEMA,
        create_type=False,
    )
    tenant_type_enum = postgresql.ENUM(
        "school",
        "independent",
        name="lectures_tenant_type_enum",
        schema=_SCHEMA,
        create_type=False,
    )
    op.create_table(
        "concept_applications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("concept_id", sa.String(length=128), nullable=False),
        sa.Column("concept_label", sa.String(length=500), nullable=False),
        sa.Column("status", status_enum, nullable=False),
        sa.Column("real_world_uses", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("career_link_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("mini_sim_prompt", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("regen_cost_usd", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("prompt_version", sa.String(length=64), nullable=True),
        sa.Column("tenant_type", tenant_type_enum, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(now() AT TIME ZONE 'UTC')"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(now() AT TIME ZONE 'UTC')"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "concept_id", "tenant_type", name="concept_applications_concept_tenant_uq"
        ),
        schema=_SCHEMA,
    )
    op.create_index(
        "ix_concept_applications_status_generated_at",
        "concept_applications",
        ["status", "generated_at"],
        schema=_SCHEMA,
    )


def downgrade() -> None:
    op.drop_index(
        "ix_concept_applications_status_generated_at",
        table_name="concept_applications",
        schema=_SCHEMA,
    )
    op.drop_table("concept_applications", schema=_SCHEMA)
    op.execute(f"DROP TYPE IF EXISTS {_SCHEMA}.concept_applications_status_enum")
