"""School migration: student_simulation_progress (T-189).

Revision ID: school_0078
Revises: school_0077
Create Date: 2026-10-03

Purpose: per-student mini-simulation state, unique (student_user_id,
concept_id) (flow-6 §3.10, T-191).
Risk: low — additive table.
Reversible: yes

Autogenerated from SchoolStudentSimulationProgress and pruned to this table.
"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "school_0078"
down_revision: str = "school_0077"
branch_labels: tuple[()] = ()
depends_on: str | None = None

_SCHEMA = "school"


def upgrade() -> None:
    tenant_type_enum = postgresql.ENUM(
        "school",
        "independent",
        name="lectures_tenant_type_enum",
        schema=_SCHEMA,
        create_type=False,
    )
    op.create_table(
        "student_simulation_progress",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("student_user_id", sa.String(length=36), nullable=False),
        sa.Column("concept_id", sa.String(length=128), nullable=False),
        sa.Column("sim_state", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("tenant_type", tenant_type_enum, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(now() AT TIME ZONE 'UTC')"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(now() AT TIME ZONE 'UTC')"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["student_user_id"], ["school.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "student_user_id",
            "concept_id",
            name="student_simulation_progress_student_concept_uq",
        ),
        schema=_SCHEMA,
    )
    op.create_index(
        "ix_student_simulation_progress_student_user_id",
        "student_simulation_progress",
        ["student_user_id"],
        schema=_SCHEMA,
    )
    op.create_index(
        "ix_student_simulation_progress_concept_id",
        "student_simulation_progress",
        ["concept_id"],
        schema=_SCHEMA,
    )


def downgrade() -> None:
    op.drop_index(
        "ix_student_simulation_progress_student_user_id",
        table_name="student_simulation_progress",
        schema=_SCHEMA,
    )
    op.drop_index(
        "ix_student_simulation_progress_concept_id",
        table_name="student_simulation_progress",
        schema=_SCHEMA,
    )
    op.drop_table("student_simulation_progress", schema=_SCHEMA)
