"""School migration: lecture_ratings (T-192).

Revision ID: school_0079
Revises: school_0078
Create Date: 2026-10-03

Purpose: optional 1-5 lecture rating on completion (flow-6 §3.11); one row per
(lecture, student); lectures → lecture_ratings CASCADE per ARCH §4.6;
CHECK rating BETWEEN 1 AND 5 (ARCH §4.15).
Risk: low — additive table.
Reversible: yes

Autogenerated from SchoolLectureRating and pruned to this table only.
"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "school_0079"
down_revision: str = "school_0078"
branch_labels: tuple[()] = ()
depends_on: str | None = None

_SCHEMA = "school"


def upgrade() -> None:
    tenant_type_enum = postgresql.ENUM(
        "school",
        "independent",
        name="lectures_tenant_type_enum",
        schema=_SCHEMA,
        create_type=False,
    )
    op.create_table(
        "lecture_ratings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("lecture_id", sa.String(length=36), nullable=False),
        sa.Column("student_user_id", sa.String(length=36), nullable=False),
        sa.Column("lecture_version_id", sa.String(length=36), nullable=True),
        sa.Column("rating", sa.SmallInteger(), nullable=False),
        sa.Column("tenant_type", tenant_type_enum, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(now() AT TIME ZONE 'UTC')"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(now() AT TIME ZONE 'UTC')"),
            nullable=False,
        ),
        sa.CheckConstraint("rating BETWEEN 1 AND 5", name="lecture_ratings_value_check"),
        sa.ForeignKeyConstraint(["lecture_id"], ["school.lectures.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["lecture_version_id"], ["school.lecture_versions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["student_user_id"], ["school.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "lecture_id", "student_user_id", name="lecture_ratings_lecture_student_uq"
        ),
        schema=_SCHEMA,
    )
    for name, cols in (
        ("ix_lecture_ratings_lecture_id", ["lecture_id"]),
        ("ix_lecture_ratings_lecture_version_id", ["lecture_version_id"]),
        ("ix_lecture_ratings_student_user_id", ["student_user_id"]),
    ):
        op.create_index(name, "lecture_ratings", cols, schema=_SCHEMA)


def downgrade() -> None:
    for name in (
        "ix_lecture_ratings_student_user_id",
        "ix_lecture_ratings_lecture_version_id",
        "ix_lecture_ratings_lecture_id",
    ):
        op.drop_index(name, table_name="lecture_ratings", schema=_SCHEMA)
    op.drop_table("lecture_ratings", schema=_SCHEMA)
