"""Tests for District and School models (T-028).

Model-level tests: table identity, schema placement, id auto-generation, soft-delete
defaults, the district FK (ON DELETE RESTRICT), and the uniqueness invariants. Per the
agreed §3.3 interpretation these tables are NOT tenant-scoped, so the cross-tenant
denial test (§3.13) attaches to the first tenant-scoped table, not to these roots —
a guard test below pins that decision in place.
"""

from __future__ import annotations

from typing import cast

from sqlalchemy import ForeignKeyConstraint, Table, UniqueConstraint

from app.features.schools.models import District, School

# `Model.__table__` is typed as FromClause; cast to Table for .constraints/.indexes.
DISTRICTS: Table = cast(Table, District.__table__)
SCHOOLS: Table = cast(Table, School.__table__)


def test_districts_table_identity() -> None:
    """District maps to school.districts."""
    assert District.__tablename__ == "districts"
    assert DISTRICTS.schema == "school"


def test_schools_table_identity() -> None:
    """School maps to school.schools."""
    assert School.__tablename__ == "schools"
    assert SCHOOLS.schema == "school"


def test_district_id_autogenerated() -> None:
    """District id is auto-generated as a UUID at construction."""
    district = District(name="Lahore District")
    assert district.id is not None
    assert len(district.id) == 36
    assert district.deleted_at is None
    assert district.is_deleted is False


def test_school_id_autogenerated() -> None:
    """School id is auto-generated as a UUID at construction."""
    school = School(district_id="d-1", name="City School")
    assert school.id is not None
    assert len(school.id) == 36
    assert school.deleted_at is None
    assert school.is_deleted is False


def test_school_district_fk_is_restrict() -> None:
    """schools.district_id references school.districts.id with ON DELETE RESTRICT."""
    fks = list(SCHOOLS.foreign_keys)
    assert len(fks) == 1
    fk = fks[0]
    assert fk.column.table.schema == "school"
    assert fk.column.table.name == "districts"
    assert fk.column.name == "id"
    assert fk.ondelete == "RESTRICT"


def test_school_district_id_not_nullable() -> None:
    """A school must belong to a district."""
    assert SCHOOLS.c.district_id.nullable is False


def test_district_name_unique() -> None:
    """District names are globally unique."""
    uniques = {c.name for c in DISTRICTS.constraints if isinstance(c, UniqueConstraint)}
    assert "districts_name_uq" in uniques


def test_school_name_unique_within_district() -> None:
    """School names are unique within a district (not globally)."""
    by_name = {
        c.name: tuple(col.name for col in c.columns)
        for c in SCHOOLS.constraints
        if isinstance(c, UniqueConstraint)
    }
    assert by_name.get("schools_district_name_uq") == ("district_id", "name")


def test_schools_district_id_indexed() -> None:
    """The district_id FK column is indexed (§4.6 — index every FK)."""
    index_names = {idx.name for idx in SCHOOLS.indexes}
    assert "ix_schools_district_id" in index_names


def test_root_tables_are_not_tenant_scoped() -> None:
    """Per ARCH §3.3 districts/schools are tenant roots — no tenant scope columns.

    This pins the agreed interpretation: no school_id/district_id/tenant_id scope
    column on these tables (and therefore no RLS). If a future change adds tenant
    scoping here, this test should fail and force a deliberate review.
    """
    for table in (DISTRICTS, SCHOOLS):
        cols = set(table.c.keys())
        assert "tenant_id" not in cols
        assert "school_id" not in cols
    # districts has no FK at all; schools' only FK is the parent district link.
    assert not any(isinstance(c, ForeignKeyConstraint) for c in DISTRICTS.constraints)
